title: Soil Moisture and the Land Energy Balance
description: The following website outlines the investigation of the change of energy in a surface soil layer, from SMAP L4 data, through the individual contributing components in relation to the surface soil moisture. 
show_downloads: true 
google_analytics:
theme: jekyll-theme-modernist
