remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#theme: jekyll-theme-minimal

title: Variability of Leaf Area Index and Vegetation Greenness Fraction
description: The following website traverses the process of determing how the Leaf Area Index and Vegetation Greenness Fraction from SMAP L4 data varies with other climatological variables. 
